name: CI-CD-Proyecto_JK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    # El tipo de m치quina virtual donde se ejecutar치 el job
    runs-on: ubuntu-latest

    # Los pasos que componen el job
    steps:
      # 1. Clona tu repositorio en la m치quina virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ms-front:${{ github.run_number }} ./ms-front
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-front:${{ github.run_number }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ms-front:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/ms-front:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-front:latest

      - name: Build and push api image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ms-api:${{ github.run_number }} ./ms-api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-api:${{ github.run_number }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ms-api:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/ms-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-api:latest

      - name: Build and push data image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ms-data:${{ github.run_number }} ./ms-data
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-data:${{ github.run_number }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ms-data:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/ms-data:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ms-data:latest
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      NAMESPACE: jessica-cuenca-dev
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OC CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
          sudo mv oc /usr/local/bin/
          oc version

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      - name: Log in Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm1.0a51.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Verify chart path
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la
          echo "Listing comment-system-chart:"
          ls -la comment-system-chart || echo "No se encontr칩 la carpeta del chart"

      - name: Move to repo root
        run: cd "${GITHUB_WORKSPACE}" && ls -la
      
      - name: Helm install or upgrade Deploy frontend
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current path: $(pwd)"
          ls -la
          helm upgrade --install front-chart ./comment-system-chart/front-chart \
            --namespace ${NAMESPACE} -f comment-system-chart/front-chart/values.yaml

      - name: Deploy backend API
        working-directory: ${{ github.workspace }}
        run: |
          helm upgrade --install backend-chart ./comment-system-chart/backend-chart \
            --namespace ${NAMESPACE} -f comment-system-chart/backend-chart/values.yaml

      - name: Deploy dataBase
        working-directory: ${{ github.workspace }}
        run: |
          helm upgrade --install dataBase-chart ./comment-system-chart/dataBase-chart \
            --namespace ${NAMESPACE} -f comment-system-chart/dataBase-chart/values.yaml
